spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 7s
      quiet-period: 5s
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/webcrawlerdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect